import { addMessages } from 'svelte-i18n';
import type { Dictionary } from './messages';

export const enDict: Dictionary = {
  'app.title': 'Travel Days',
  // Common
  'common.back': 'Back',
  'common.select': 'Select',
  'common.accept': 'Accept',
  'common.available_variants': 'Available variants',
  'common.optional': 'optional',
  'common.loading': 'Loading...',
  'common.synchronizing': 'Synchronizing',
  'common.show_more': 'Show more',
  'common.sorting': 'Sorting',
  'common.sort_by': 'Sort by',
  'common.sort_direction': 'Sort direction',
  'common.ascending': 'Ascending',
  'common.descending': 'Descending',
  'common.grouping': 'Grouping',
  'common.no_items': 'No items yet',
  'common.nothing_found': 'Nothing found',
  'common.create': 'Create',
  'common.save': 'Save',
  'common.add': 'Add',
  'common.save_changes_failure': 'Failed to save changes',
  'common.save_changes_success': 'Changes were saved',
  'common.search': 'Search',
  'common.clear': 'Clear',
  'common.close': 'Close',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.ok': 'OK',
  'common.done': 'Done',
  'common.continue': 'Continue',
  'common.reset': 'Reset',
  'common.go_back_to_list': 'Go back to list',
  'common.count': '{count} pcs.',
  'common.show': 'Show',
  'common.hide': 'Hide',
  'common.data_problems': 'Data storage initialization finished with {count, plural, =1 {# error} other {# errors}}',
  'common.select_all': 'Select all',
  'common.date_and_time': 'Date and time',
  // Trips
  'trips.title': 'Trips',
  'trips.add.title': 'New trip',
  'trips.add.trip_type': 'Trip type',
  'trips.add.departure': 'Departure',
  'trips.add.arrival': 'Arrival',
  'trips.add.additional_info': 'Additional info',
  'trips.add.airplane': 'Plane',
  'trips.add.car': 'Car',
  'trips.add.ship': 'Ship',
  'trips.add.from': 'From',
  'trips.add.from_placeholder': 'Select departure point',
  'trips.add.to': 'To',
  'trips.add.to_placeholder': 'Select destination point',
  'trips.add.country': 'Country',
  'trips.add.city': 'City',
  'trips.add.airport': 'Airport',
  'trips.add.country_placeholder': 'Select country',
  'trips.add.city_placeholder': 'Select city',
  'trips.add.airport_placeholder': 'Select airport',
  'trips.add.departure_point_required': 'Select departure point',
  'trips.add.arrival_point_required': 'Select destination point',
  'trips.add.departure_date_time_required': 'Select departure date',
  'trips.add.arrival_date_time_required': 'Select arrival date',
  'trips.edit.title': 'Edit trip',
  'trips.edit.delete_trip': 'Delete trip',
  // Timezones
  'timezones.select_time_zone': 'Select time zone',
  'timezones.current_time_zone': 'Current time zone',
  'timezones.favorite_time_zones': 'Favorite time zones',
  'timezones.all_time_zones': 'All time zones',
  'timezones.timezone_added_to_favorites': 'Time zone was added to favorites',
  'timezones.timezone_removed_from_favorites': 'Time zone was removed from favorites',
  // Tags
  'tags.add_modal_header': 'Add tag',
  'tags.edit_modal_header': 'Edit tag',
  'tags.title': 'Title',
  'tags.delete_tag': 'Delete tag',
  'tags.add_tag_failure': 'Failed to add tag',
  'tags.edit_tag_failure': 'Failed to edit tag',
  'tags.delete_tag_failure': 'Failed to delete tag',
  // Language
  'language.select_language': 'Select language',
  // Auth
  'auth.login.title': 'Login',
  'auth.login': 'Login',
  'auth.password': 'Password',
  'auth.sign_in': 'Sign in',
  'auth.incorrect_login_or_password': 'Incorrect login or password',
  'auth.incorrect_old_password': 'Incorrect old password',
  'auth.failed_to_login': 'Failed to login',
  'auth.register.title': 'Register',
  'auth.name': 'Name',
  'auth.phone': 'Phone',
  'auth.old_password': 'Old password',
  'auth.new_password': 'New password',
  'auth.repeat_password': 'Repeat password',
  'auth.passwords_must_be_same': 'Passwords must be same',
  'auth.register': 'Sign up',
  'auth.user_already_exists': 'User already exists',
  'auth.registration_success': 'Registration was successful',
  'auth.registration_failure': 'Failed to register',
  'auth.logout.title': 'Logout',
  'auth.logging_out': 'Logging out...',
  'auth.sign_out': 'Sign out',
  'auth.profile': 'Profile',
  'auth.logged_in_as': 'You are logged in as {name}!',
  'auth.not_logged_in': 'You are not logged in',
  'auth.continue_as_guest': 'Continue as a guest',
  'auth.logged_in_as_guest_info': "You're are using app as a guest. Data won't be sync with server.",
  'auth.guest': 'Guest',
  // Settings
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.select_language': 'Select language',
  'settings.common': 'Common',
  'settings.darkMode': 'Dark mode',
  'settings.theme': 'Theme',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.theme.system': 'System',
  'settings.import_export': 'Import / Export',
  'settings.profile': 'Profile',
  'settings.profile.change_name': 'Change name',
  'settings.profile.change_name_failure': 'Failed to change name',
  'settings.profile.change_login': 'Change login',
  'settings.profile.change_login_failure': 'Failed to change login',
  'settings.profile.change_password': 'Change password',
  'settings.profile.change_password_success': 'Password was changed',
  'settings.profile.change_password_failure': 'Failed to change password',
  'settings.profile.change_workspace': 'Select workspace',
  'settings.profile.change_workspace_failure': 'Failed to select workspace',
  'settings.profile.logout': 'Log out',
  'settings.collaboration': 'Collaboration',
  'settings.collaboration.workspace': 'Workspace',
  'settings.collaboration.workspaces': 'Workspaces',
  'settings.collaboration.invites': 'Invites',
  'settings.collaboration.blocklist': 'Blocklist',
  'settings.debug_tools': 'Debug tools',
  'settings.logs': 'Logs',
  'settings.logs.filters': 'Filters',
  'settings.logs.show_filters': 'Show filters',
  'settings.logs.hide_filters': 'Hide filters',
  'settings.encryption': 'Encryption',
  'settings.report_problem': 'Report a problem',
  'settings.version': 'Version: {version}',
  'settings.uikit': 'UI Kit',
};

addMessages('en-US', enDict);
